export const SkillsProgramming = [
  "_React",
  "_React Native",
  "_Redux",
  "_Javascript",
  "_Typescript",
  "_API REST | Axios",
  "_HTML",
  "_SCSS",
  "_Figma",
  "_Material UI",
  "_Next JS",
  "_GraphQL",
  "_Git | GitHub",
  "_Agile methodologies",
  "_Linux",
  "_BashShell",
  "_XML - JSON",
  "_PHP - MVC",
  "_MySQL",
  "_PostgreSQL",
  "_Java",
  "_SpringBoot",
];